### PR TITLE
SymbolicWedderburn v0.3 -> v0.4

### PR DESCRIPTION
**Pull request by blegat**
Closes https://github.com/jump-dev/SumOfSquares.jl/pull/352

### CODE REVIEW

**Comment by kalmarek** [comment]
@blegat how to turn `MonomialBasis{Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}, MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}}` into an actual vector?

**Comment by kalmarek** [comment]
also something is rather odd here:
```julia
    basis = SumOfSquares.Certificate.gram_basis(cert.certificate, poly)
    @info eltype(basis)
```
shows `Any` ?

**Comment by blegat** [comment]
Maybe we could define `eltype` I think I didn't do it since it's not an `AbstractVector`. By the way, an `StarAlgebras.AbstractBasis` is also not an `AbstractVector` so probably that will remain the case right ?
```julia
julia> basis = MonomialBasis(monomials([x, y], 2))
MonomialBasis([y², xy, x²])

julia> generators(basis)
3-element MonomialVector{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}:
 y²
 xy
 x²

julia> generators(basis) isa AbstractVector
true

julia> eltype(generators(basis))
Monomial{DynamicPolynomials.Commutative{DynamicPolynomials.CreationOrder}, Graded{LexOrder}}
```

**Comment by kalmarek** [comment]
at the moment it's enough for basis to get an honest vector that's it.

We'll overhaul the whole thing in the near future, so there's no need to define the API for the old version, right?

**Comment by blegat** [comment]
No, no need, this PR can sit here and wait for StarAlgebras

**Comment by blegat** [comment]
I bumped in https://github.com/jump-dev/SumOfSquares.jl/pull/355 even if it's not working but I'll wait for https://github.com/kalmarek/SymbolicWedderburn.jl/issues/79

**Pull request closed without merging**
