### PR TITLE
Bl/update symbolicwedderburn

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by blegat** [comment]
The issues seems to be the first element of the basis:
```julia
julia> basis = MB.maxdegree_basis(MB.MonomialBasis, [x, y], 3)
MonomialBasis{Monomial{true}, MonomialVector{true}}(Monomial{true}[x³, x²y, xy², y³, x², xy, y², x, y, 1])

julia> B = SymbolicWedderburn.symmetry_adapted_basis(Float64, DihedralGroup(4), DihedralAction(), basis)
4-element Vector{SymbolicWedderburn.DirectSummand{Float64, Matrix{Float64}}}:
 [0.7071067811865472 0.0 … 0.0 0.0; 0.0 0.7071067811865472 … 0.0 0.0; 0.0 0.0 … 0.7071067811865475 0.0]
 [0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 1.0]
 [0.0 0.0 … 0.0 0.0]
 [0.0 0.0 … 0.0 0.0]

julia> B[1]
3×10 SymbolicWedderburn.DirectSummand{Float64, Matrix{Float64}}:
 0.707107  0.0       0.0       0.707107  0.0  0.0  0.0  0.0       0.0       0.0
 0.0       0.707107  0.707107  0.0       0.0  0.0  0.0  0.0       0.0       0.0
 0.0       0.0       0.0       0.0       0.0  0.0  0.0  0.707107  0.707107  0.0

julia> B[2]
2×10 SymbolicWedderburn.DirectSummand{Float64, Matrix{Float64}}:
 0.0  0.0  0.0  0.0  0.707107  0.0  0.707107  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0       0.0  0.0       0.0  0.0  1.0

julia> B[3]
1×10 SymbolicWedderburn.DirectSummand{Float64, Matrix{Float64}}:
 0.0  0.0  0.0  0.0  0.0  -1.0  0.0  0.0  0.0  0.0

julia> B[4]
1×10 SymbolicWedderburn.DirectSummand{Float64, Matrix{Float64}}:
 0.0  0.0  0.0  0.0  -0.707107  0.0  0.707107  0.0  0.0  0.0

julia> round.(B[1].basis * basis.monomials * √2)
3-element Vector{Polynomial{true, Float64}}:
 x³ + y³
 x²y + xy²
 x + y
```
Before, it used to give 6 elements with these 6 monomials. Then, since the degree is 2, I would split it into `[x³, x²y, x]` and `[y³, xy², y]`. Here, why are they summed ?
Is it possible that it's an incorrect handling of the complex -> real (where the sum would come from complex conjugate pairs) ? (just a wild guess)

**Comment by kalmarek** [comment]
@blegat cool, thanks for the analysis

**Comment by kalmarek** [comment]
@blegat This is not a problem with handling complex → real, since all characters of `Sym(3)` are real (the one of degree 2 for the dihedral group is real too?) but I've noticed something similar there. E.g.
```
3-element Vector{Polynomial{true, Rational{Int64}}}:
 x₁ - x₄
 x₂ - x₄
 x₃ - x₄
```
becomes
```
1-element Vector{Polynomial{true, Rational{Int64}}}:
 x₁ - 1//3x₂ - 1//3x₃ - 1//3x₄
```
(if you switch `x₄` with `x₁` and flip signs that's taking the average of the above). And indeed the `rank_one_projection(χ, ...)` of the corresponding character is
```
1//3·() +1//3·(2,4,3) +1//3·(2,3,4)
```

The worst (best? :D ) thing is that this seems to be mathematically correct ;) we're interested in projection to one dimensional subspace of the 3-dim space above. The average of basis vectors seems to be just ok, doesn't it? The same applies to the dihedral basis above. And yet something is off here, since i translated my old code (for the creation of symmetrized sdp) to this setting and it returns infeasible as well ;/

**Comment by blegat** [comment]
Since it's deg 2 and multiplicity 3, we need a semisimple of 6 elements, or 2 simple ones of 3 elements each. Here there is only one of 3 elements so something's missing :-P

**Comment by kalmarek** [comment]
hmm, sticking to the dihedral example: 
the projection onto semi-simple summand is of rank `6`. We know that inside there are `3` simple components each of degree `2`, so the final psd constraint will be of size `3×3`. So `sa_basis` gives you a subspace of rank `3`. This is not the decomposition into simple summands (three of them), it's the projection picking 1-dimensional subspace from each of simple summands.

**Comment by blegat** [comment]
> it's the projection picking 1-dimensional subspace from each of simple summands.

How to I get the rest of the subspace ? One option would be applying the generators. Let the generators be `d` mapping `(x, y)` to `-y, x` and `s` mapping `x, y` to `y, x`. `x + y -s-> y + x` so that doesn't give anything new however `x + y -d-> `-y + x`. Now `<x + y, x - y> = <x, y>` so we're back at the same subspace. So I guess we could use `x + y` as the first basis element of the first 3x3 psd constraint and `x - y` as the second one. Should it be SumOfSquares or SymbolicWedderburn that does this task ?

**Comment by kalmarek** [comment]
In principle You don't need the rest of the space to formulate e.g. gramm-based sos problem; You need though it to reconstruct the original Gramm matrix I recall (by averaging over group). Let's schedule a meeging, shall we?

**Pull request merged**
