### PR TITLE
Update for SymbolicWedderburn#38

### PR DESCRIPTION
**Pull request by blegat**
I made an update to https://github.com/kalmarek/SymbolicWedderburn.jl/pull/38. Here are the current failures even with the changes of this PR:
```jl
julia> include("src/tutorials/Symmetry/even_reduction.jl")
ERROR: LoadError: MethodError: no method matching svd!(::SparseArrays.SparseMatrixCSC{Float64, Int64})
Closest candidates are:
  svd!(::LinearAlgebra.AbstractTriangular; kwargs...) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/triangular.jl:2212
  svd!(::StridedMatrix{T}; full, alg) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:92
  svd!(::StridedMatrix{T}, ::StridedMatrix{T}) where T<:Union{Float32, Float64, ComplexF32, ComplexF64} at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/svd.jl:361
  ...
Stacktrace:
  [1] image_basis!(A::SparseArrays.SparseMatrixCSC{Float64, Int64})
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/eigenspacedecomposition.jl:96
  [2] image_basis(hom::SymbolicWedderburn.CachedExtensionHomomorphism{OnSign, Monomial{true}, Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{OnSign, Monomial{true}, Int64, Vector{Monomial{true}}}}, χ::SymbolicWedderburn.Character{Float64, Int64, SymbolicWedderburn.CharacterTable{PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, Nothing}}})
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:9
  [3] (::SymbolicWedderburn.var"#103#105"{DataType, SymbolicWedderburn.CachedExtensionHomomorphism{OnSign, Monomial{true}, Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{OnSign, Monomial{true}, Int64, Vector{Monomial{true}}}}})(::Tuple{SymbolicWedderburn.Character{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Int64, SymbolicWedderburn.CharacterTable{PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, Nothing}}}, Int64})
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:216
  [4] iterate
    @ ./generator.jl:47 [inlined]
  [5] collect(itr::Base.Generator{Base.Iterators.Zip{Tuple{Vector{SymbolicWedderburn.Character{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Int64, SymbolicWedderburn.CharacterTable{PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, Nothing}}}}, Vector{Int64}}}, SymbolicWedderburn.var"#103#105"{DataType, SymbolicWedderburn.CachedExtensionHomomorphism{OnSign, Monomial{true}, Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{OnSign, Monomial{true}, Int64, Vector{Monomial{true}}}}}})
    @ Base ./array.jl:678
  [6] map(f::Function, A::Base.Iterators.Zip{Tuple{Vector{SymbolicWedderburn.Character{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Int64, SymbolicWedderburn.CharacterTable{PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, Nothing}}}}, Vector{Int64}}})
    @ Base ./abstractarray.jl:2323
  [7] symmetry_adapted_basis(T::Type, tbl::SymbolicWedderburn.CharacterTable{PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{Permutation{Int64, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}}, Nothing}}, action::OnSign, basis::MonomialBasis{Monomial{true}, MonomialVector{true}}; semisimple::Bool)
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:213
  [8] #symmetry_adapted_basis#101
    @ ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:194 [inlined]
  [9] symmetry_adapted_basis (repeats 2 times)
    @ ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:193 [inlined]
 [10] get(cert::SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{SOSCone, MonomialBasis, Tuple{}}, PermGroup{Int64, StabilizerChain{Int64, Perm{Int64}, Schreier{Perm{Int64}, Int64, Int64, PermutationGroups.Orbit1{Int64, Int64}, typeof(^)}}}, OnSign}, attr::SumOfSquares.Certificate.GramBasis, poly::Polynomial{true, MathOptInterface.ScalarAffineFunction{Float64}})
    @ SumOfSquares.Certificate.Symmetry ~/.julia/dev/SumOfSquares/src/Certificate/Symmetry/wedderburn.jl:91

julia> include("src/tutorials/Symmetry/dihedral_symmetry_of_the_robinson_form.jl")
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
SymbolicWedderburn.action(DihedralAction(), g, poly) = x⁶ - x⁴y² - x²y⁴ + y⁶ - x⁴ + 3x²y² - y⁴ - x² - y² + 1
ERROR: LoadError: MethodError: no method matching matrix_projection(::SymbolicWedderburn.CachedExtensionHomomorphism{DihedralAction, Monomial{true}, DihedralElement, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{DihedralAction, Monomial{true}, Int64, Vector{Monomial{true}}}}, ::StarAlgebras.AlgebraElement{StarAlgebras.StarAlgebra{DihedralGroup, DihedralElement, StarAlgebras.CachedMTable{DihedralElement, UInt16, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}, Matrix{UInt16}, false}, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}}, Float64, Vector{Float64}})
Closest candidates are:
  matrix_projection(::SymbolicWedderburn.InducedActionHomomorphism{var"#s126", T} where {var"#s126"<:SymbolicWedderburn.ByPermutations, T}, ::StarAlgebras.AlgebraElement) at /home/blegat/.julia/dev/SymbolicWedderburn/src/projections.jl:94
  matrix_projection(::SymbolicWedderburn.InducedActionHomomorphism{var"#s125", T} where {var"#s125"<:SymbolicWedderburn.ByPermutations, T}, ::StarAlgebras.AlgebraElement, ::Any) at /home/blegat/.julia/dev/SymbolicWedderburn/src/projections.jl:94
  matrix_projection(::StarAlgebras.AlgebraElement{var"#s124", T, V} where {var"#s124"<:(StarAlgebras.StarAlgebra{var"#s123", T, M, B} where {var"#s123"<:AbstractAlgebra.AbstractPermutationGroup, T, M<:StarAlgebras.MultiplicativeStructure, B<:(StarAlgebras.AbstractBasis{T, I} where I)}), T, V<:AbstractVector{T}}, ::Any) at /home/blegat/.julia/dev/SymbolicWedderburn/src/projections.jl:112
Stacktrace:
  [1] image_basis(hom::SymbolicWedderburn.CachedExtensionHomomorphism{DihedralAction, Monomial{true}, DihedralElement, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{DihedralAction, Monomial{true}, Int64, Vector{Monomial{true}}}}, α::StarAlgebras.AlgebraElement{StarAlgebras.StarAlgebra{DihedralGroup, DihedralElement, StarAlgebras.CachedMTable{DihedralElement, UInt16, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}, Matrix{UInt16}, false}, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}}, Float64, Vector{Float64}})
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:19
  [2] (::SymbolicWedderburn.var"#104#106"{DataType, SymbolicWedderburn.CachedExtensionHomomorphism{DihedralAction, Monomial{true}, DihedralElement, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{DihedralAction, Monomial{true}, Int64, Vector{Monomial{true}}}}})(::Tuple{StarAlgebras.AlgebraElement{StarAlgebras.StarAlgebra{DihedralGroup, DihedralElement, StarAlgebras.CachedMTable{DihedralElement, UInt16, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}, Matrix{UInt16}, false}, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Vector{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}}}, Int64, Int64, Bool})
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:229
  [3] iterate
    @ ./generator.jl:47 [inlined]
  [4] collect(itr::Base.Generator{Base.Iterators.Zip{Tuple{Vector{StarAlgebras.AlgebraElement{StarAlgebras.StarAlgebra{DihedralGroup, DihedralElement, StarAlgebras.CachedMTable{DihedralElement, UInt16, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}, Matrix{UInt16}, false}, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Vector{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}}}}, Vector{Int64}, Vector{Int64}, BitVector}}, SymbolicWedderburn.var"#104#106"{DataType, SymbolicWedderburn.CachedExtensionHomomorphism{DihedralAction, Monomial{true}, DihedralElement, SparseArrays.SparseMatrixCSC{Float64, Int64}, SymbolicWedderburn.ExtensionHomomorphism{DihedralAction, Monomial{true}, Int64, Vector{Monomial{true}}}}}})
    @ Base ./array.jl:678
  [5] map(f::Function, A::Base.Iterators.Zip{Tuple{Vector{StarAlgebras.AlgebraElement{StarAlgebras.StarAlgebra{DihedralGroup, DihedralElement, StarAlgebras.CachedMTable{DihedralElement, UInt16, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}, Matrix{UInt16}, false}, StarAlgebras.Basis{DihedralElement, UInt16, Vector{DihedralElement}}}, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, Vector{Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}}}}, Vector{Int64}, Vector{Int64}, BitVector}})
    @ Base ./abstractarray.jl:2323
  [6] symmetry_adapted_basis(T::Type, tbl::SymbolicWedderburn.CharacterTable{DihedralGroup, Cyclotomics.Cyclotomic{Rational{Int64}, SparseArrays.SparseVector{Rational{Int64}, Int64}}, PermutationGroups.Orbit1{DihedralElement, Nothing}}, action::DihedralAction, basis::MonomialBasis{Monomial{true}, MonomialVector{true}}; semisimple::Bool)
    @ SymbolicWedderburn ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:227
  [7] #symmetry_adapted_basis#101
    @ ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:194 [inlined]
  [8] symmetry_adapted_basis (repeats 2 times)
    @ ~/.julia/dev/SymbolicWedderburn/src/sa_basis.jl:193 [inlined]
  [9] get(cert::SumOfSquares.Certificate.Symmetry.Ideal{SumOfSquares.Certificate.Newton{SOSCone, MonomialBasis, Tuple{}}, DihedralGroup, DihedralAction}, attr::SumOfSquares.Certificate.GramBasis, poly::Polynomial{true, MathOptInterface.ScalarAffineFunction{Float64}})
    @ SumOfSquares.Certificate.Symmetry ~/.julia/dev/SumOfSquares/src/Certificate/Symmetry/wedderburn.jl:91
```

### CODE REVIEW

**Comment by blegat** [comment]
Indeed, it works with that branch. What doesn't work anymore is `DihedralGroup2`. It seems that you now need to implement `iterate` even if you implement `conjugacy_classes_orbit` ?

**Comment by kalmarek** [comment]
so all three examples are working locally; I guess we just need to release SymbolicWedderburn?

**Comment by blegat** [comment]
> I guess we just need to release SymbolicWedderburn?

Yes, go for it :)

**Comment by kalmarek** [comment]
> > I guess we just need to release SymbolicWedderburn?
> 
> Yes, go for it :)

Done!

**Pull request merged**
